'use client'

import { BoardsProvider } from '@/contexts/BoardsContext'
import { Roboto } from 'next/font/google'
import './globals.css'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '500'],
})

export const metadata = {
  title: 'Kanban',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <BoardsProvider>
          {children}
        </BoardsProvider>
      </body>
    </html>
  )
}
